<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Day</name>
   <tag></tag>
   <elementGuidId>af20e5a1-522a-4150-8e3e-a6fc22a19d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='days']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#days</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5771d891-d366-425f-8545-6dba76eb9b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>bd95805a-e7e6-4d75-8ae0-e9a4e7f7c5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>a7f13e0e-cc79-4dc1-b218-0ff6c1899044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>7a49c7f2-80dd-4b53-8de0-22a77cb14dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0b504818-839c-4cd5-a28f-5486416fb73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											</value>
      <webElementGuid>215f8b78-049a-4b52-970c-1cd6fe9d44e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;days&quot;)</value>
      <webElementGuid>2b931d32-256b-4024-8c37-a608396e31fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='days']</value>
      <webElementGuid>d3f3a183-f2f4-43b6-ad01-b1a105e3d7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-days']/select</value>
      <webElementGuid>6c5f68e2-e844-4926-8166-a117cd6f2b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[1]</value>
      <webElementGuid>bd1851fc-8597-439e-a7c8-e176857869f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>baf307c9-11ec-4cda-8d54-334c3b410c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for our newsletter!'])[1]/preceding::select[3]</value>
      <webElementGuid>01ba3160-7175-4892-a86e-908e7c7ff0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive special offers from our partners!'])[1]/preceding::select[3]</value>
      <webElementGuid>974d8b1c-9244-4e0c-890b-298135055d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2b3ca339-b515-4631-be2a-715e8cc481ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'days' and @name = 'days' and (text() = '
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											' or . = '
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											')]</value>
      <webElementGuid>6dbfc754-3d29-4b85-a5f5-180725578db1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
